// export const navLinks = [
//   {
//     title: "Home",
//     link: "/",
//     isButton: false,
//     isLink: true,
//     isNested: false,
//     isExternal: false,
//     isDisabled: false,
//     hasIcon: false,
//     icon: "",
//     isAuth: false,
//   },
//   {
//     title: "Contact",
//     link: "/contact",
//     isButton: false,
//     isLink: true,
//     isNested: false,
//     isExternal: false,
//     isDisabled: false,
//     hasIcon: false,
//     icon: "",
//     isAuth: false,
//   },
//   {
//     title: "About",
//     link: "/About",
//     isButton: false,
//     isLink: true,
//     isNested: false,
//     isExternal: false,
//     isDisabled: false,
//     hasIcon: false,
//     icon: "",
//     isAuth: false,
//   },
//   {
//     title: "Forms",
//     link: "/forms",
//     isButton: false,
//     isLink: true,
//     isNested: true,
//     isExternal: false,
//     isDisabled: false,
//     hasIcon: false,
//     icon: "",
//     isAuth: false,
//   },
// ];


export const navLinks = [
  {
    "title": "Home",
    "link": "/",
    "isButton": false,
    "isLink": true,
    "isNested": false,
    "isExternal": false,
    "isDisabled": false,
    "hasIcon": false,
    "icon": "",
    "isAuth": false
  },
  {
    "title": "Contact",
    "link": "/contact",
    "isButton": false,
    "isLink": true,
    "isNested": false,
    "isExternal": false,
    "isDisabled": false,
    "hasIcon": false,
    "icon": "",
    "isAuth": false
  },
  {
    "title": "About",
    "link": "/about",
    "isButton": false,
    "isLink": true,
    "isNested": false,
    "isExternal": false,
    "isDisabled": false,
    "hasIcon": false,
    "icon": "",
    "isAuth": false
  },
  {
    "title": "Forms",
    "link": "/forms",
    "isButton": false,
    "isLink": true,
    "isNested": true,
    "isExternal": false,
    "isDisabled": false,
    "hasIcon": false,
    "icon": "",
    "isAuth": false,
    "nestedLinks": [
      {
        "title": "KIIT Form",
        "link": "/forms/kiit",
        "isButton": false,
        "isLink": true,
        "isNested": false,
        "isExternal": false,
        "isDisabled": false,
        "hasIcon": false,
        "icon": "",
        "isAuth": false
      },
      {
        "title": "Another Form",
        "link": "/forms/another",
        "isButton": false,
        "isLink": true,
        "isNested": false,
        "isExternal": false,
        "isDisabled": false,
        "hasIcon": false,
        "icon": "",
        "isAuth": false
      }
    ]
  },
  {
    "title": "External Link",
    "link": "https://example.com",
    "isButton": false,
    "isLink": true,
    "isNested": false,
    "isExternal": true,
    "isDisabled": false,
    "hasIcon": false,
    "icon": "",
    "isAuth": false
  },
  {
    "title": "Disabled Link",
    "link": "#",
    "isButton": false,
    "isLink": true,
    "isNested": false,
    "isExternal": false,
    "isDisabled": true,
    "hasIcon": false,
    "icon": "",
    "isAuth": false
  },
  {
    "title": "Auth Required",
    "link": "/dashboard",
    "isButton": false,
    "isLink": true,
    "isNested": false,
    "isExternal": false,
    "isDisabled": false,
    "hasIcon": false,
    "icon": "",
    "isAuth": true
  },
  {
    "title": "Action Button",
    "link": "/action",
    "isButton": true,
    "isLink": false,
    "isNested": false,
    "isExternal": false,
    "isDisabled": false,
    "hasIcon": false,
    "icon": "",
    "isAuth": false
  }
]
